# Generated by Django 3.2.6 on 2021-11-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20211119_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 14, 38, 7, 540024)),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.TextField(default=''),
        ),
    ]
