# Generated by Django 3.2.6 on 2021-11-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20211119_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at']},
        ),
    ]
