# Generated by Django 3.2.6 on 2021-11-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20211125_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
