# Generated by Django 3.2.6 on 2021-11-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
