# Generated by Django 3.2.6 on 2021-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20211207_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, ''), (1, 'Finance'), (2, 'IT'), (3, 'Metallurgy'), (3, 'Food')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='visitor', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.ManyToManyField(to='Main.Industry'),
        ),
    ]
