# Generated by Django 3.2.6 on 2021-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_auto_20211221_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.IntegerField(choices=[(0, ''), (1, 'Finance'), (2, 'IT'), (3, 'Metallurgy'), (3, 'Food')]),
        ),
    ]
