# Generated by Django 3.2.6 on 2021-12-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_alter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Finance'), (2, 'IT')]),
        ),
    ]
