# Generated by Django 3.2.6 on 2021-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_alter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')], default='EUR'),
        ),
    ]
