# Generated by Django 3.2.6 on 2021-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')]),
        ),
    ]
