# Generated by Django 3.2.6 on 2021-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Visitor'), (2, 'User'), (3, 'Premium'), (4, 'Vip'), (4, 'Admin')]),
        ),
    ]
