# Generated by Django 3.2.6 on 2021-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='Hi!, Welcome to my IBCA page!'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.ManyToManyField(blank=True, to='Main.Industry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Visitor'), (2, 'User'), (3, 'Premium'), (4, 'Vip'), (4, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=64),
        ),
    ]
