# Generated by Django 3.2.6 on 2021-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_viewnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.IntegerField(choices=[(1, 'Russia'), (2, 'USA'), (3, 'Italy'), (3, 'Germany')], default=1),
        ),
    ]
