# Generated by Django 3.2.6 on 2021-12-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewnote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.user'),
        ),
    ]
