# Generated by Django 3.2.6 on 2022-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_alter_viewnote_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Finance'), (2, 'IT')], null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_ru',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Finance'), (2, 'IT')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_ru',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city_en',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city_ru',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_en',
            field=models.IntegerField(choices=[(1, 'Russia'), (2, 'USA'), (3, 'Italy'), (3, 'Germany')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_ru',
            field=models.IntegerField(choices=[(1, 'Russia'), (2, 'USA'), (3, 'Italy'), (3, 'Germany')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency_en',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency_ru',
            field=models.IntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'RUB')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description_en',
            field=models.TextField(default='Hi!, Welcome to my IBCA page!', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description_ru',
            field=models.TextField(default='Hi!, Welcome to my IBCA page!', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_en',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_ru',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_en',
            field=models.IntegerField(choices=[(1, 'Visitor'), (2, 'User'), (3, 'Premium'), (4, 'Vip'), (4, 'Admin')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_ru',
            field=models.IntegerField(choices=[(1, 'Visitor'), (2, 'User'), (3, 'Premium'), (4, 'Vip'), (4, 'Admin')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='views_count_en',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='views_count_ru',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode_en',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode_ru',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
