# Generated by Django 3.2.6 on 2022-01-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_auto_20220116_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_ru',
        ),
    ]
